
obj-$(CONFIG_ARCH_TCC898X) += vioc_rdma.o vioc_wdma.o vioc_wmix.o vioc_vin.o
obj-$(CONFIG_ARCH_TCC898X) += vioc_scaler.o vioc_viqe.o vioc_lut.o vioc_mc.o
obj-$(CONFIG_ARCH_TCC898X) += vioc_api.o vioc_intr.o vioc_ireq.o
obj-$(CONFIG_ARCH_TCC898X) += vioc_config.o vioc_disp.o vioc_outcfg.o
obj-$(CONFIG_ARCH_TCC898X) += of_vioc_rdma.o of_vioc_wmix.o of_vioc_sc.o of_vioc_wdma.o
obj-$(CONFIG_ARCH_TCC898X) += tccfb_address.o
obj-$(CONFIG_ARCH_TCC898X) += update_cbcr_asm.o
#obj-$(CONFIG_ARCH_TCC898X) += vioc_power.o

obj-$(CONFIG_FB_TCC)			+= TCC_LCD_Interface.o tca_lcdc.o
obj-$(CONFIG_FB_TCC_COMPOSITE)	+= tcc_composite.o tcc_composite_internal.o 
obj-$(CONFIG_FB_TCC_COMPONENT)	+= tcc_component.o tcc_component_ths8200.o
obj-$(CONFIG_ARCH_TCC896X)		+= tca_map_converter.o
obj-$(CONFIG_ARCH_TCC897X)		+= tca_map_converter.o
obj-$(CONFIG_ARCH_TCC_MAP_CONVERTER)		+= tca_map_converter.o
