obj-$(CONFIG_TCCXXXX_LINUXTV_INTERFACE) := tcc_dxb_drv.o

tcc_dxb_drv-objs := tcc_dxb_kernel.o \
                    tcc_fe.o \
                    tcc_tsif_interface.o \
                    tcc_dmx.o

EXTRA_CFLAGS := -Idrivers/media/dvb-core
