#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_336S_AT) += atmel/
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT401) += melfas_mip4/
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw/
obj-$(CONFIG_TOUCHSCREEN_SERDES_INIT) += serdes/
