obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT_336S_AT)	+= atmel_mxt336S_AT.o
atmel_mxt336S_AT-objs := atmel_mxt336S.o atmel_mxt336S_cfg.o atmel_mxt336S_parse.o
CFLAGS_atmel_mxt336S.o := -DDEBUG -Wno-unused-variable
