#
# Makefile for the kernel character device drivers.
#
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/irq.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/phy/phy.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/bsp/i2cm.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/main_controller.o
#obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/api/api.o

obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_video.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/video_packetizer.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/edid/dtd.o

obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/video_params.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/video_sampler.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_avi.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_gamut.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_debug.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/csc.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/video.o

obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/audio.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/audio_i2s.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/audio_spdif.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/audio_params.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/audio_multistream.o

obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_audio.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_audio_info.o

obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_packets.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_acp.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_isrc.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_spd.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/fc_vsd.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/product.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/core/packets.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/scdc/scdc.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/scdc/scrambling.o
obj-$(CONFIG_TCC_HDMI_DRIVER_V2_0)	+=  src/api/api.o

