#ifndef __LINUX_IBOX_API_SUBMICOM_FUNCTION_H__
#define __LINUX_IBOX_API_SUBMICOM_FUNCTION_H__

#define IBOX_SUBMICOM_IOC_MAGIC_V1	'S'

#define IBOX_SUBMICOMIOC_CLEAR_BUFFER \
		_IO(IBOX_SUBMICOM_IOC_MAGIC_V1, 0)

#endif /* __LINUX_IBOX_API_SUBMICOM_FUNCTION_H__ */
