#
# Makefile for kernel H/W Demux drivers.
#
obj-$(CONFIG_SPI_TCCXXXX_TSIF_SLAVE) += tca_hwdemux_tsif.o
obj-$(CONFIG_SPI_TCCXXXX_TSIF_SLAVE) += tca_hwdemux_cmd.o
#obj-$(CONFIG_SPI_TCCXXXX_TSIF_SLAVE) += tca_hwdemux_cipher_cmd.o
