obj-y	+= vioc_disp.o vioc_outcfg.o vioc_rdma.o vioc_wdma.o vioc_wmix.o vioc_deintls.o vioc_fifo.o
obj-y	+= vioc_viqe.o vioc_scaler.o vioc_ireq.o vioc_api.o vioc_config.o vioc_mc.o
obj-y	+= vioc_vin.o vioc_lut.o update_cbcr_asm.o
obj-y	+= vioc_intr.o
obj-y	+= of_vioc_rdma.o of_vioc_wmix.o of_vioc_sc.o of_vioc_wdma.o
